### ISSUE TITLE
Contact Quality values always 0

### ISSUE THREAD

**Issue by saatvikshah1994** [openyou/emokit#135]
My contact quality values always show the value 0. What could the possible problem be?

**Comment by mnzab** [comment]
I m having the same problem. Contact quality is showing 0 for all sensors all the time. 
@saatvikshah1994 , Were you able to resolve the issue?

**Comment by ahmedfarazkhan** [comment]
@saatvikshah1994 and @mnzab, did you manage to resolve your contact quality issues?

**Comment by saatvikshah1994** [comment]
Nope I wasnt able to resolve the issue - But my Emotiv headset was a bit old and not very well maintained. That could have also been the issue.

**Comment by nathanielatom** [comment]
I tried storing the quality values as floats instead of ints (currently the code uses integer division). This gives non-zero values - mostly ~0.02 - when there are no electrodes connected. Shorting a channel to ground seems to produce a higher quality as does pressing an electrode against skin. I made a pull request #158 that includes this change.

**Comment by bschumacher** [comment]
Changed the defaults to not be a small integer and instead using a utility function to check the signal level, so now there should definitely be something other than 0 if it's on your head.
