### ISSUE TITLE
Render.py problem: Invalid color argument

### ISSUE THREAD

**Issue by felipefpx** [openyou/emokit#222]
I ran "python render.py" and I got this error:

No psyco. Expect poor performance. Not really...
Initializing Emokit...
Initializing Reader Thread...
Initializing Writer Thread(s)...
Initializing Crypto Thread...
Initializing Output Thread...
Crypto thread stopping. 
Reader stopping...
Reader stopped...
('EmotivRender ', <type 'exceptions.TypeError'>, TypeError('invalid color argument',), <traceback object at 0x10a6ee950>, ' : ', TypeError('invalid color argument',))

I removed the exception threatment and the problem is on these lines:
            71    if self.old_model:
            72       color = str(get_quality_scale_level_color(quality, True))
            73    else:
            74       color = str(get_quality_scale_level_color(quality, False))

I'm using the EPOC (first version, without Bluetooth) device and a MacMini device with MacOSX Sierra.

**Comment by xribene** [comment]
I have the same exactly problem but in windows 7 and EPOC with bluetooth

**Comment by tallhobbes** [comment]
I had this problem as well, and it seems the color needs to be a tuple, not a string. Deleting the str() wrapper around get_quality_scale_level_color(args) worked for me, since that function returns a tuple to begin with. Not sure why the string conversion is there, maybe pygame has changed its expectations? Anyway, hooray for squiggly lines!

**Comment by xribene** [comment]
this worked . thank you @tallhobbes

**Comment by bschumacher** [comment]
Apparently New implementation of Color was done in pygame 1.8.1.
